const ABI_2 = [{
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor"
}, {
    inputs: [],
    name: "ActionFailed",
    type: "error"
}, {
    inputs: [],
    name: "SlippageExceeded",
    type: "error"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "caller",
        type: "address"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "amounts",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "info",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "bytes",
        name: "filled",
        type: "bytes"
    }],
    name: "OrdersFilled",
    type: "event"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "caller",
        type: "address"
    }, {
        indexed: !1,
        internalType: "bytes",
        name: "orderData",
        type: "bytes"
    }],
    name: "OrdersUpdated",
    type: "event"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "market",
        type: "address"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "maxPrice",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "fee",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "address",
        name: "gov",
        type: "address"
    }],
    name: "ParamsChanged",
    type: "event"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "caller",
        type: "address"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "quoteAmount",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256"
    }],
    name: "RewardsClaimed",
    type: "event"
}, {
    stateMutability: "nonpayable",
    type: "fallback"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "accumulatedFeeBase",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "accumulatedFeeQuote",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "addressToUserId",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "baseAsset",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256[]",
        name: "actions",
        type: "uint256[]"
    }, {
        internalType: "uint256[]",
        name: "prices",
        type: "uint256[]"
    }, {
        internalType: "uint256[]",
        name: "param1",
        type: "uint256[]"
    }, {
        internalType: "address[]",
        name: "param2",
        type: "address[]"
    }, {
        internalType: "address",
        name: "owner",
        type: "address"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "batchOrders",
    outputs: [{
        internalType: "uint256[]",
        name: "returnData",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256[]",
        name: "actions",
        type: "uint256[]"
    }, {
        internalType: "uint256[]",
        name: "prices",
        type: "uint256[]"
    }, {
        internalType: "uint256[]",
        name: "param1",
        type: "uint256[]"
    }, {
        internalType: "address[]",
        name: "param2",
        type: "address[]"
    }, {
        internalType: "address",
        name: "owner",
        type: "address"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "batchOrdersRequireSuccess",
    outputs: [{
        internalType: "uint256[]",
        name: "returnData",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "address",
        name: "owner",
        type: "address"
    }],
    name: "cancelOrder",
    outputs: [{
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "newFee",
        type: "uint256"
    }],
    name: "changeFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "newGov",
        type: "address"
    }],
    name: "changeGov",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "newMaxPrice",
        type: "uint256"
    }],
    name: "changeMaxPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "caller",
        type: "address"
    }],
    name: "claimFees",
    outputs: [{
        internalType: "uint256",
        name: "quoteAmount",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [],
    name: "fee",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "getPrice",
    outputs: [{
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "_highestBid",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "_lowestAsk",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "bool",
        name: "isAscending",
        type: "bool"
    }, {
        internalType: "uint256",
        name: "startPrice",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "distance",
        type: "uint256"
    }],
    name: "getPriceLevels",
    outputs: [{
        internalType: "bytes",
        name: "",
        type: "bytes"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "distance",
        type: "uint256"
    }],
    name: "getPriceLevelsFromMid",
    outputs: [{
        internalType: "uint256",
        name: "_highestBid",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "_lowestAsk",
        type: "uint256"
    }, {
        internalType: "bytes",
        name: "",
        type: "bytes"
    }, {
        internalType: "bytes",
        name: "",
        type: "bytes"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "bool",
        name: "isBuy",
        type: "bool"
    }, {
        internalType: "bool",
        name: "isExactInput",
        type: "bool"
    }, {
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "worstPrice",
        type: "uint256"
    }],
    name: "getQuote",
    outputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "gov",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "highestBid",
    outputs: [{
        internalType: "uint80",
        name: "",
        type: "uint80"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "latestUserId",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "bool",
        name: "isBuy",
        type: "bool"
    }, {
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }, {
        internalType: "address",
        name: "from",
        type: "address"
    }, {
        internalType: "address",
        name: "owner",
        type: "address"
    }],
    name: "limitOrder",
    outputs: [{
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [],
    name: "lowestAsk",
    outputs: [{
        internalType: "uint80",
        name: "",
        type: "uint80"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "bool",
        name: "isBuy",
        type: "bool"
    }, {
        internalType: "bool",
        name: "isExactInput",
        type: "bool"
    }, {
        internalType: "bool",
        name: "isFromCaller",
        type: "bool"
    }, {
        internalType: "bool",
        name: "isToCaller",
        type: "bool"
    }, {
        internalType: "uint256",
        name: "orderType",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "worstPrice",
        type: "uint256"
    }, {
        internalType: "address",
        name: "caller",
        type: "address"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "marketOrder",
    outputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [],
    name: "maxPrice",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "minSize",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    name: "orders",
    outputs: [{
        internalType: "uint40",
        name: "owner",
        type: "uint40"
    }, {
        internalType: "uint128",
        name: "size",
        type: "uint128"
    }, {
        internalType: "uint40",
        name: "fillBefore",
        type: "uint40"
    }, {
        internalType: "uint40",
        name: "fillAfter",
        type: "uint40"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    name: "priceLevels",
    outputs: [{
        internalType: "uint128",
        name: "size",
        type: "uint128"
    }, {
        internalType: "uint40",
        name: "fillNext",
        type: "uint40"
    }, {
        internalType: "uint40",
        name: "latest",
        type: "uint40"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "quoteAsset",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "caller",
        type: "address"
    }],
    name: "registerUser",
    outputs: [{
        internalType: "uint256",
        name: "_latestUserId",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [],
    name: "router",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "scaleFactor",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    name: "userIdToAddress",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}]


const ROUTER_ABI = [{
    inputs: [{
        internalType: "address",
        name: "_gov",
        type: "address"
    }, {
        internalType: "address",
        name: "_WETH",
        type: "address"
    }],
    stateMutability: "nonpayable",
    type: "constructor"
}, {
    inputs: [],
    name: "CancelFailed",
    type: "error"
}, {
    inputs: [{
        internalType: "address",
        name: "tokenIn",
        type: "address"
    }, {
        internalType: "address",
        name: "tokenOut",
        type: "address"
    }, {
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }],
    name: "cancelOrder",
    outputs: [{
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "newGov",
        type: "address"
    }],
    name: "changeGov",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "address[]",
        name: "markets",
        type: "address[]"
    }],
    name: "claimFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [],
    name: "clearUsername",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "quoteAsset",
        type: "address"
    }, {
        internalType: "address",
        name: "baseAsset",
        type: "address"
    }, {
        internalType: "address",
        name: "_gov",
        type: "address"
    }, {
        internalType: "uint256",
        name: "fee",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "scaleFactor",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "minSize",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "maxPrice",
        type: "uint256"
    }],
    name: "deploy",
    outputs: [{
        internalType: "address",
        name: "market",
        type: "address"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "timestamp",
        type: "uint256"
    }],
    name: "Expired",
    type: "error"
}, {
    inputs: [{
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }],
    name: "Invalid",
    type: "error"
}, {
    inputs: [{
        internalType: "address",
        name: "asset0",
        type: "address"
    }, {
        internalType: "address",
        name: "asset1",
        type: "address"
    }],
    name: "InvalidMarket",
    type: "error"
}, {
    inputs: [],
    name: "OrderFailed",
    type: "error"
}, {
    inputs: [],
    name: "RefCodeAlreadyTaken",
    type: "error"
}, {
    inputs: [],
    name: "SlippageExceeded",
    type: "error"
}, {
    inputs: [{
        internalType: "address",
        name: "recipient",
        type: "address"
    }],
    name: "TransferFailed",
    type: "error"
}, {
    inputs: [{
        internalType: "address",
        name: "caller",
        type: "address"
    }],
    name: "Unauthorized",
    type: "error"
}, {
    inputs: [],
    name: "UsernameAlreadyTaken",
    type: "error"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !1,
        internalType: "address",
        name: "prev",
        type: "address"
    }, {
        indexed: !1,
        internalType: "address",
        name: "gov",
        type: "address"
    }],
    name: "GovChanged",
    type: "event"
}, {
    inputs: [{
        internalType: "address",
        name: "tokenIn",
        type: "address"
    }, {
        internalType: "address",
        name: "tokenOut",
        type: "address"
    }, {
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }],
    name: "limitOrder",
    outputs: [{
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }],
    stateMutability: "payable",
    type: "function"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "quoteAsset",
        type: "address"
    }, {
        indexed: !0,
        internalType: "address",
        name: "baseAsset",
        type: "address"
    }, {
        indexed: !1,
        internalType: "address",
        name: "market",
        type: "address"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "fee",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "scaleFactor",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "minSize",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "maxPrice",
        type: "uint256"
    }, {
        indexed: !1,
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    name: "MarketCreated",
    type: "event"
}, {
    inputs: [{
        internalType: "address[]",
        name: "markets",
        type: "address[]"
    }, {
        internalType: "uint256[][]",
        name: "action",
        type: "uint256[][]"
    }, {
        internalType: "uint256[][]",
        name: "price",
        type: "uint256[][]"
    }, {
        internalType: "uint256[][]",
        name: "param1",
        type: "uint256[][]"
    }, {
        internalType: "address[][]",
        name: "param2",
        type: "address[][]"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "multiBatchOrders",
    outputs: [{
        internalType: "uint256[][]",
        name: "returnData",
        type: "uint256[][]"
    }],
    stateMutability: "payable",
    type: "function"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "referrer",
        type: "address"
    }, {
        indexed: !1,
        internalType: "address",
        name: "referee",
        type: "address"
    }],
    name: "Referral",
    type: "event"
}, {
    inputs: [{
        internalType: "bool",
        name: "postOnly",
        type: "bool"
    }, {
        internalType: "address",
        name: "tokenIn",
        type: "address"
    }, {
        internalType: "address",
        name: "tokenOut",
        type: "address"
    }, {
        internalType: "uint256",
        name: "price",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "newPrice",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "newSize",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "replaceOrder",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "string",
        name: "code",
        type: "string"
    }],
    name: "setReferral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "string",
        name: "code",
        type: "string"
    }],
    name: "setUsedRef",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "string",
        name: "username",
        type: "string"
    }],
    name: "setUsername",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "bool",
        name: "exactInput",
        type: "bool"
    }, {
        internalType: "address",
        name: "tokenIn",
        type: "address"
    }, {
        internalType: "address",
        name: "tokenOut",
        type: "address"
    }, {
        internalType: "uint256",
        name: "orderType",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "size",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "worstPrice",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swap",
    outputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "id",
        type: "uint256"
    }],
    stateMutability: "payable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapETHForExactTokens",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "payable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapExactETHForTokens",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "payable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapExactTokensForETH",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapExactTokensForTokens",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountInMax",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapTokensForExactETH",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "amountInMax",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }, {
        internalType: "address",
        name: "to",
        type: "address"
    }, {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
    }, {
        internalType: "address",
        name: "referrer",
        type: "address"
    }],
    name: "swapTokensForExactTokens",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "nonpayable",
    type: "function"
}, {
    anonymous: !1,
    inputs: [{
        indexed: !0,
        internalType: "address",
        name: "caller",
        type: "address"
    }, {
        indexed: !1,
        internalType: "string",
        name: "username",
        type: "string"
    }],
    name: "Username",
    type: "event"
}, {
    stateMutability: "payable",
    type: "receive"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "addressToRef",
    outputs: [{
        internalType: "string",
        name: "",
        type: "string"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "addressToReferrer",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "addressToUsername",
    outputs: [{
        internalType: "string",
        name: "",
        type: "string"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    name: "allMarkets",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "allMarketsLength",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "ETH",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountOut",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }],
    name: "getAmountsIn",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "uint256",
        name: "amountIn",
        type: "uint256"
    }, {
        internalType: "address[]",
        name: "path",
        type: "address[]"
    }],
    name: "getAmountsOut",
    outputs: [{
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }, {
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "getMarket",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "gov",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }, {
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "index",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "parameters",
    outputs: [{
        internalType: "address",
        name: "quoteAsset",
        type: "address"
    }, {
        internalType: "address",
        name: "baseAsset",
        type: "address"
    }, {
        internalType: "address",
        name: "gov",
        type: "address"
    }, {
        internalType: "address",
        name: "router",
        type: "address"
    }, {
        internalType: "uint256",
        name: "fee",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "scaleFactor",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "minSize",
        type: "uint256"
    }, {
        internalType: "uint256",
        name: "maxPrice",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    name: "referrerToReferredAddresses",
    outputs: [{
        internalType: "uint256",
        name: "",
        type: "uint256"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "string",
        name: "",
        type: "string"
    }],
    name: "refToAddress",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [{
        internalType: "string",
        name: "",
        type: "string"
    }],
    name: "usernameToAddress",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}, {
    inputs: [],
    name: "WETH",
    outputs: [{
        internalType: "address",
        name: "",
        type: "address"
    }],
    stateMutability: "view",
    type: "function"
}]

module.exports = {
  ROUTER_ABI
};

